### ISSUE TITLE
Feil typehint i Parallel.map() og starmap()

### ISSUE THREAD

**Issue by Bjoern-Rapp** [statisticsnorway/ssb-sgis#161]
Det er feil typehint for variabelen `iterable` i metoden `Parallel.map()` og `Parallel.starmap()`. Typehintet er `Iterable`. Det er ikke forventet at en `collections.abc.Iterable` har noen `__len__()` metode, men i `Parallel.map()` og `Parallel.starmap()` brukes `len()` på `iterable`. [`collections.abc.Collection`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Collection) er riktig typehint for en variable som både er itererbar og har en størrelse.

**Comment by mortewle** [comment]
Så ikke denne før nå, men flott!
